services:
- type: web
  repo: https://github.com/mohammadalkhawaldah/livekit-voice-assistant

  # Path containing your Dockerfile
  rootDir: backend

  name: agent-backend
  runtime: docker

  # Free plan is not available for private services
  plan: starter

  # Environment variables are stored in a group created in the Render dashboard.
  envVars:
  - fromGroup: agent-example-env
  region: virginia

  # 300s is the standard allowed maximum.
  maxShutdownDelaySeconds: 300

version: "1"
